2020-10-23 14:05:29,967 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 14:05:53,533 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 14:19:06,195 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 14:20:37,197 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 14:22:54,008 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 14:23:59,042 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 14:27:02,541 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 14:27:55,383 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 14:28:32,534 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 14:34:21,416 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 14:35:37,228 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 14:39:14,730 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 14:42:09,130 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 14:46:37,964 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 14:59:42,849 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 15:03:26,120 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 15:06:36,764 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 15:07:45,412 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 15:09:34,358 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 15:19:26,953 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 15:28:39,860 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 15:38:09,950 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 15:40:08,508 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 15:42:29,097 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 15:45:46,009 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 15:49:08,039 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 15:50:46,787 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 15:52:52,103 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 15:53:38,174 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 15:59:58,248 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 16:02:09,531 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 16:05:37,001 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 16:19:18,586 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 16:23:08,185 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 16:27:17,986 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 16:28:10,247 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 16:28:40,496 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 16:29:54,148 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 16:31:23,130 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 16:31:52,911 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 16:32:59,088 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 16:34:30,416 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 16:36:30,801 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 16:38:23,867 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 16:46:40,399 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 16:47:26,572 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 16:48:44,060 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 16:49:38,103 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 16:52:41,923 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 16:53:57,140 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 16:58:08,008 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 16:59:30,503 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 16:59:57,772 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 17:05:39,433 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 17:18:15,263 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 18:02:01,639 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 18:03:41,687 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 18:04:30,831 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 18:06:31,386 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 18:06:58,205 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 18:13:51,318 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-23 18:15:09,690 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-26 09:09:16,960 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-26 09:11:04,499 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-26 09:12:57,736 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-26 09:16:17,224 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-26 09:18:24,001 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-26 09:19:12,622 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-26 09:21:18,069 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-26 15:15:27,915 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-26 15:18:15,440 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-26 15:19:59,148 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-26 15:20:36,062 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-26 15:21:43,172 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-26 15:23:00,483 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-26 15:23:47,398 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-26 15:24:36,329 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-26 15:29:12,203 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-26 15:30:08,931 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-26 15:45:11,336 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-26 15:46:33,321 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-26 15:52:30,128 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-26 15:55:22,110 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-26 16:03:25,199 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-26 16:29:32,780 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-26 17:09:12,361 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-26 17:46:57,399 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-26 17:48:08,098 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-26 17:49:14,651 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-26 17:50:23,269 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-26 17:51:08,900 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-26 17:51:55,598 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-26 18:05:04,210 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-26 18:08:31,025 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-26 18:09:02,676 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-26 18:13:52,073 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-26 18:14:13,779 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-26 18:15:28,959 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-26 18:31:37,519 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-26 18:32:08,032 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-26 18:33:17,611 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-26 18:33:35,456 - [test_login.py-->line:104] - ERROR:
Traceback (most recent call last):
  File "F:\guoyou\U盘\Desktop\liukai\cashier_ui_fr\testcases\test_login.py", line 98, in test001_login
    assert login_sucees_text == login_success
AssertionError
2020-10-27 09:11:00,212 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 09:11:08,914 - [test_login.py-->line:104] - ERROR:
Traceback (most recent call last):
  File "F:\guoyou\U盘\Desktop\liukai\cashier_ui_fr\testcases\test_login.py", line 98, in test001_login
    assert login_sucees_text == login_success
AssertionError
2020-10-27 09:12:46,502 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 09:36:31,550 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 09:40:15,335 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 09:51:03,431 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 09:51:15,405 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 09:51:39,364 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 09:53:18,752 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 09:53:58,501 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 09:56:47,010 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 10:07:18,491 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 10:09:55,071 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 10:10:58,301 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 10:10:59,732 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 10:12:29,816 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 10:13:27,681 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 10:16:23,443 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 10:18:48,027 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 10:19:10,197 - [test_browse_goods.py-->line:58] - ERROR:用例{}执行通过
2020-10-27 10:19:41,551 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 10:24:57,983 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 10:26:26,799 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 10:26:48,027 - [test_browse_goods.py-->line:58] - INFO:用例{}执行通过
2020-10-27 10:27:35,065 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 10:27:56,876 - [test_browse_goods.py-->line:58] - INFO:用例test001_Browse_Goods执行通过
2020-10-27 10:29:18,501 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 10:29:27,409 - [test_login.py-->line:110] - INFO:用例test001_login执行通过
2020-10-27 10:35:01,756 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 10:35:23,459 - [test_browse_goods.py-->line:58] - INFO:用例test001_Browse_Goods执行通过
2020-10-27 10:35:36,673 - [test_login.py-->line:110] - INFO:用例test001_login执行通过
2020-10-27 11:27:19,324 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 11:28:03,952 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 11:46:28,163 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 11:47:58,499 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 11:49:12,270 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 12:03:19,994 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 13:54:28,543 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 13:56:02,326 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 14:04:01,340 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 14:04:55,816 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 14:10:41,221 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 14:12:18,956 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 14:12:48,010 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 14:15:56,470 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 14:16:20,133 - [test_add_goods.py-->line:79] - ERROR:用例test001_Browse_Goods执行不通过
2020-10-27 14:16:20,133 - [test_add_goods.py-->line:81] - ERROR:
Traceback (most recent call last):
  File "F:\guoyou\U盘\Desktop\liukai\cashier_ui_fr\testcases\test_add_goods.py", line 76, in test001_Browse_Goods
    assert add_success_text == "添加成功"
AssertionError
2020-10-27 14:17:45,532 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 14:18:09,181 - [test_add_goods.py-->line:79] - ERROR:用例test001_Browse_Goods执行不通过
2020-10-27 14:18:09,181 - [test_add_goods.py-->line:81] - ERROR:
Traceback (most recent call last):
  File "F:\guoyou\U盘\Desktop\liukai\cashier_ui_fr\testcases\test_add_goods.py", line 76, in test001_Browse_Goods
    assert add_success_text == "添加成功"
AssertionError
2020-10-27 14:20:53,531 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 14:21:18,855 - [test_add_goods.py-->line:85] - INFO:用例test001_add_goods执行通过
2020-10-27 14:25:38,269 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 14:26:46,719 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 14:28:20,457 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 14:28:45,557 - [test_edit_goods.py-->line:83] - INFO:用例test001_add_goods执行通过
2020-10-27 14:30:06,955 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 14:30:32,281 - [test_add_goods.py-->line:85] - INFO:用例test01_add_goods执行通过
2020-10-27 14:30:58,602 - [test_browse_goods.py-->line:58] - INFO:用例test01_browse_goods执行通过
2020-10-27 14:31:28,762 - [test_edit_goods.py-->line:83] - INFO:用例test01_edit_goods执行通过
2020-10-27 14:31:42,988 - [test_login.py-->line:110] - INFO:用例test01_login执行通过
2020-10-27 14:39:25,433 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 14:39:50,249 - [test_add_goods.py-->line:85] - INFO:用例test01_add_goods执行通过
2020-10-27 14:40:15,716 - [test_browse_goods.py-->line:59] - INFO:用例test01_browse_goods执行通过
2020-10-27 14:40:43,332 - [test_edit_goods.py-->line:83] - INFO:用例test01_edit_goods执行通过
2020-10-27 14:40:56,270 - [test_login.py-->line:110] - INFO:用例test01_login执行通过
2020-10-27 15:42:03,794 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 15:52:20,382 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 15:53:12,063 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 15:55:01,779 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 15:56:01,766 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 15:57:31,791 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 15:59:00,916 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 16:02:00,557 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 16:03:39,530 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 16:04:21,173 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 16:06:45,980 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 16:09:27,805 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 16:16:20,393 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 16:18:18,838 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 16:25:36,725 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 16:26:19,580 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 16:27:01,234 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 16:29:26,556 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 16:39:18,539 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 16:40:12,199 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 16:41:40,381 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 17:04:15,288 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 17:05:58,885 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 17:20:38,391 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 17:21:21,482 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-27 17:23:33,972 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-28 09:17:17,975 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-28 10:43:16,416 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-28 10:44:12,440 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-28 10:45:52,049 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-28 10:49:19,080 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-28 10:50:52,052 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-28 10:52:52,137 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-28 10:53:53,792 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-28 10:55:45,242 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-28 11:07:12,596 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-28 11:11:56,655 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-28 11:13:21,304 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-28 11:42:38,476 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-28 11:43:25,238 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-28 11:50:50,088 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-28 11:52:31,876 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-28 11:53:14,805 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-28 11:54:21,997 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-28 11:57:18,371 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-28 11:59:42,283 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-28 15:30:40,441 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-28 15:36:34,000 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-28 15:40:28,399 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-28 15:41:42,939 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-28 15:43:04,904 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-28 15:51:10,949 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-28 15:52:35,532 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-28 15:53:42,953 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-28 16:03:37,164 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-28 16:04:10,446 - [test_add_online_goods.py-->line:114] - ERROR:用例test01_add_online_goods执行不通过
2020-10-28 16:04:10,446 - [test_add_online_goods.py-->line:116] - ERROR:
Traceback (most recent call last):
  File "F:\guoyou\U盘\Desktop\liukai\cashier_ui_fr\testcases\test_add_online_goods.py", line 111, in test01_add_online_goods
    assert submit_text == "添加成功"
AssertionError
2020-10-28 16:05:37,567 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-28 16:07:56,111 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-28 16:08:57,038 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-28 16:09:31,970 - [test_add_online_goods.py-->line:115] - ERROR:用例test01_add_online_goods执行不通过
2020-10-28 16:09:31,971 - [test_add_online_goods.py-->line:117] - ERROR:
Traceback (most recent call last):
  File "F:\guoyou\U盘\Desktop\liukai\cashier_ui_fr\testcases\test_add_online_goods.py", line 112, in test01_add_online_goods
    assert submit_text == "添加成功"
AssertionError
2020-10-28 16:10:38,143 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-28 16:11:13,793 - [test_add_online_goods.py-->line:120] - INFO:用例test01_add_online_goods执行通过
2020-10-29 10:04:07,161 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 10:06:07,755 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 10:09:22,019 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 10:12:57,955 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 10:13:50,250 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 10:16:56,026 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 10:17:40,150 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 10:19:01,941 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 10:22:16,234 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 10:23:09,803 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 10:34:39,544 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 10:34:50,515 - [test_login.py-->line:110] - INFO:用例test01_login执行通过
2020-10-29 10:35:26,150 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 10:35:34,306 - [test_login.py-->line:111] - INFO:用例test01_login执行通过
2020-10-29 10:38:47,255 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 10:39:33,146 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 10:42:36,914 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 10:44:20,053 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 10:48:34,380 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 11:08:27,097 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 11:20:18,817 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 11:21:05,420 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 11:21:45,077 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 11:23:18,637 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 11:24:01,704 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 11:24:43,259 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 11:29:49,219 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 11:30:46,808 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 11:49:05,288 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 11:50:05,197 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 11:51:35,895 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 11:53:00,306 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 12:00:36,348 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 12:01:46,095 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 12:03:11,136 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 12:07:09,039 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 12:12:18,480 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 12:12:58,245 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 12:13:37,977 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 13:32:03,159 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 13:45:58,344 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 13:46:40,539 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 14:10:22,194 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 14:12:12,209 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 14:13:06,362 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 14:44:16,042 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 14:46:04,366 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 14:46:56,244 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 14:47:42,440 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 14:48:31,389 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 14:50:53,005 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 14:52:23,558 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 14:55:02,133 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 14:57:37,436 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 14:57:39,412 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 14:59:29,225 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 15:02:43,049 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 15:03:57,229 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 15:09:28,433 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 15:11:50,001 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 15:25:37,509 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 15:26:00,483 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 15:26:49,405 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 15:28:42,422 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 15:31:31,486 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 15:32:05,840 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 15:32:39,962 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 15:33:14,080 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 15:34:30,041 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 15:38:17,785 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 15:40:35,239 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 15:44:04,247 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 15:44:40,135 - [test_add_online_goods.py-->line:120] - INFO:用例test01_add_online_goods执行通过
2020-10-29 15:44:50,946 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 15:45:26,201 - [test_add_online_goods.py-->line:115] - ERROR:用例test01_add_online_goods执行不通过
2020-10-29 15:45:26,201 - [test_add_online_goods.py-->line:117] - ERROR:
Traceback (most recent call last):
  File "F:\guoyou\U盘\Desktop\liukai\cashier_ui_fr\testcases\test_add_online_goods.py", line 112, in test01_add_online_goods
    assert submit_text == "添加成功"
AssertionError
2020-10-29 15:47:51,636 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 15:48:27,521 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 15:49:02,930 - [test_add_online_goods.py-->line:120] - INFO:用例test01_add_online_goods执行通过
2020-10-29 15:49:35,338 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 15:50:07,220 - [test_delete_online_goods.py-->line:94] - INFO:用例test01_delete_online_goods执行通过
2020-10-29 17:33:45,883 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-29 17:34:25,211 - [test_add_online_goods.py-->line:120] - INFO:用例test01_add_online_goods执行通过
2020-10-30 10:30:11,405 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-30 10:31:08,392 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-30 10:32:34,980 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-30 10:44:29,226 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-30 10:45:13,207 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-30 10:45:57,625 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-30 10:46:54,623 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-30 10:47:53,378 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-30 10:49:14,042 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-30 10:50:28,480 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-30 10:51:09,543 - [test_add_online_goods.py-->line:122] - INFO:用例test01_add_online_goods执行通过
2020-10-30 10:52:08,184 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-30 10:52:51,116 - [test_add_online_goods.py-->line:117] - ERROR:用例test01_add_online_goods执行不通过
2020-10-30 10:52:51,116 - [test_add_online_goods.py-->line:119] - ERROR:
Traceback (most recent call last):
  File "F:\guoyou\U盘\Desktop\liukai\cashier_ui_fr\testcases\test_add_online_goods.py", line 114, in test01_add_online_goods
    assert submit_text == "添加成功"
AssertionError
2020-10-30 10:54:01,473 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-30 10:54:47,114 - [test_add_online_goods.py-->line:117] - ERROR:用例test01_add_online_goods执行不通过
2020-10-30 10:54:47,114 - [test_add_online_goods.py-->line:119] - ERROR:
Traceback (most recent call last):
  File "F:\guoyou\U盘\Desktop\liukai\cashier_ui_fr\testcases\test_add_online_goods.py", line 114, in test01_add_online_goods
    assert submit_text == "添加成功"
AssertionError
2020-10-30 10:58:42,098 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-30 10:59:55,298 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-30 11:01:18,886 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-30 11:03:10,599 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-30 11:03:58,469 - [test_add_online_goods.py-->line:122] - INFO:用例test01_add_online_goods执行通过
2020-10-30 11:04:36,288 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-30 11:06:17,663 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-30 11:06:53,475 - [test_add_online_goods.py-->line:117] - ERROR:用例test01_add_online_goods执行不通过
2020-10-30 11:06:53,476 - [test_add_online_goods.py-->line:119] - ERROR:
Traceback (most recent call last):
  File "F:\guoyou\U盘\Desktop\liukai\cashier_ui_fr\testcases\test_add_online_goods.py", line 114, in test01_add_online_goods
    assert submit_text == "添加成功"
AssertionError
2020-10-30 11:29:06,709 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-30 11:29:42,427 - [test_add_online_goods.py-->line:117] - ERROR:用例test01_add_online_goods执行不通过
2020-10-30 11:29:42,427 - [test_add_online_goods.py-->line:119] - ERROR:
Traceback (most recent call last):
  File "F:\guoyou\U盘\Desktop\liukai\cashier_ui_fr\testcases\test_add_online_goods.py", line 114, in test01_add_online_goods
    assert submit_text == "添加成功"
AssertionError
2020-10-30 11:42:36,490 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-30 11:43:12,003 - [test_add_online_goods.py-->line:117] - ERROR:用例test01_add_online_goods执行不通过
2020-10-30 11:43:12,003 - [test_add_online_goods.py-->line:119] - ERROR:
Traceback (most recent call last):
  File "F:\guoyou\U盘\Desktop\liukai\cashier_ui_fr\testcases\test_add_online_goods.py", line 114, in test01_add_online_goods
    assert submit_text == "添加成功"
AssertionError
2020-10-30 11:45:02,269 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-30 11:45:37,788 - [test_add_online_goods.py-->line:117] - ERROR:用例test01_add_online_goods执行不通过
2020-10-30 11:45:37,788 - [test_add_online_goods.py-->line:119] - ERROR:
Traceback (most recent call last):
  File "F:\guoyou\U盘\Desktop\liukai\cashier_ui_fr\testcases\test_add_online_goods.py", line 114, in test01_add_online_goods
    assert submit_text == "添加成功"
AssertionError
2020-10-30 11:47:55,014 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-30 11:49:05,501 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-30 11:49:41,510 - [test_add_online_goods.py-->line:122] - INFO:用例test01_add_online_goods执行通过
2020-10-30 11:52:57,653 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-30 11:53:33,469 - [test_add_online_goods.py-->line:117] - ERROR:用例test01_add_online_goods执行不通过
2020-10-30 11:53:33,469 - [test_add_online_goods.py-->line:119] - ERROR:
Traceback (most recent call last):
  File "F:\guoyou\U盘\Desktop\liukai\cashier_ui_fr\testcases\test_add_online_goods.py", line 114, in test01_add_online_goods
    assert submit_text == "添加成功"
AssertionError
2020-10-30 14:12:09,760 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-30 14:12:46,350 - [test_add_online_goods.py-->line:117] - ERROR:用例test01_add_online_goods执行不通过
2020-10-30 14:12:46,350 - [test_add_online_goods.py-->line:119] - ERROR:
Traceback (most recent call last):
  File "F:\guoyou\U盘\Desktop\liukai\cashier_ui_fr\testcases\test_add_online_goods.py", line 114, in test01_add_online_goods
    assert submit_text == "添加成功"
AssertionError
2020-10-30 14:13:31,376 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-30 14:14:08,156 - [test_add_online_goods.py-->line:117] - ERROR:用例test01_add_online_goods执行不通过
2020-10-30 14:14:08,156 - [test_add_online_goods.py-->line:119] - ERROR:
Traceback (most recent call last):
  File "F:\guoyou\U盘\Desktop\liukai\cashier_ui_fr\testcases\test_add_online_goods.py", line 114, in test01_add_online_goods
    assert submit_text == "添加成功"
AssertionError
2020-10-30 14:17:36,311 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-30 14:18:12,163 - [test_add_online_goods.py-->line:117] - ERROR:用例test01_add_online_goods执行不通过
2020-10-30 14:18:12,163 - [test_add_online_goods.py-->line:119] - ERROR:
Traceback (most recent call last):
  File "F:\guoyou\U盘\Desktop\liukai\cashier_ui_fr\testcases\test_add_online_goods.py", line 114, in test01_add_online_goods
    assert submit_text == "添加成功"
AssertionError
2020-10-30 14:18:36,634 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-30 14:19:13,009 - [test_add_online_goods.py-->line:117] - ERROR:用例test01_add_online_goods执行不通过
2020-10-30 14:19:13,009 - [test_add_online_goods.py-->line:119] - ERROR:
Traceback (most recent call last):
  File "F:\guoyou\U盘\Desktop\liukai\cashier_ui_fr\testcases\test_add_online_goods.py", line 114, in test01_add_online_goods
    assert submit_text == "添加成功"
AssertionError
2020-10-30 14:19:35,898 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-30 14:20:13,100 - [test_add_online_goods.py-->line:117] - ERROR:用例test01_add_online_goods执行不通过
2020-10-30 14:20:13,100 - [test_add_online_goods.py-->line:119] - ERROR:
Traceback (most recent call last):
  File "F:\guoyou\U盘\Desktop\liukai\cashier_ui_fr\testcases\test_add_online_goods.py", line 114, in test01_add_online_goods
    assert submit_text == "添加成功"
AssertionError
2020-10-30 14:20:51,054 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-30 14:21:28,849 - [test_add_online_goods.py-->line:117] - ERROR:用例test01_add_online_goods执行不通过
2020-10-30 14:21:28,849 - [test_add_online_goods.py-->line:119] - ERROR:
Traceback (most recent call last):
  File "F:\guoyou\U盘\Desktop\liukai\cashier_ui_fr\testcases\test_add_online_goods.py", line 114, in test01_add_online_goods
    assert submit_text == "添加成功"
AssertionError
2020-10-30 14:21:50,391 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-30 14:22:29,100 - [test_add_online_goods.py-->line:117] - ERROR:用例test01_add_online_goods执行不通过
2020-10-30 14:22:29,100 - [test_add_online_goods.py-->line:119] - ERROR:
Traceback (most recent call last):
  File "F:\guoyou\U盘\Desktop\liukai\cashier_ui_fr\testcases\test_add_online_goods.py", line 114, in test01_add_online_goods
    assert submit_text == "添加成功"
AssertionError
2020-10-30 14:30:01,988 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-30 14:30:38,965 - [test_add_online_goods.py-->line:117] - ERROR:用例test01_add_online_goods执行不通过
2020-10-30 14:30:38,965 - [test_add_online_goods.py-->line:119] - ERROR:
Traceback (most recent call last):
  File "F:\guoyou\U盘\Desktop\liukai\cashier_ui_fr\testcases\test_add_online_goods.py", line 114, in test01_add_online_goods
    assert submit_text == "添加成功"
AssertionError
2020-10-30 14:45:32,890 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-30 14:46:59,525 - [handlelog.py-->line:39] - INFO:调试一下下
2020-10-30 14:47:35,175 - [test_add_online_goods.py-->line:117] - ERROR:用例test01_add_online_goods执行不通过
2020-10-30 14:47:35,175 - [test_add_online_goods.py-->line:119] - ERROR:
Traceback (most recent call last):
  File "F:\guoyou\U盘\Desktop\liukai\cashier_ui_fr\testcases\test_add_online_goods.py", line 114, in test01_add_online_goods
    assert submit_text == "添加成功"
AssertionError
